version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci

  pre_build:
    commands:
      - echo "Running lint (optional)..."
      - npm run lint || echo "Lint warnings ignored"

  build:
    commands:
      - echo "Building Vite + React + Tailwind app..."
      - npm run build
      - echo "Build completed."

  post_build:
    commands:
      - echo "Zipping production build artifacts..."
      - zip -r vite-react-app.zip dist/
      - echo "Post-build steps complete."

artifacts:
  files:
    - vite-react-app.zip
  base-directory: dist
  discard-paths: no

